name: Execute Test Manualy

on:
  workflow_dispatch:

jobs:
  ExecuteTests:

    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/java:v1.45.0-jammy

    steps:
    - uses: actions/checkout@v3
    - name: Verify Maven Version 
      run: mvn --version
      
    - name: Execute automated test cases
      run: mvn test -PGrid

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Cucumber Reports
        path: target/Reports
